title: ðŸ“„ Docs as Flashcards âš¡
description: For devs bored to tears by docs who need to learn them anyways ðŸ˜­
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Repository: https://github.com/asa55/docs-as-flashcards/
