title: 3Ddocs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://github.com/harrynow83/3Ddocs

aux_links:
  Template Repository: https://github.com/harrynow83/3Ddocs

color_scheme: dark
# otras opciones Ãºtiles (opcional)
# nav_sort: case_insensitive
